on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Continuous integration

jobs:

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Install SDL2
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
      - uses: actions/cache@v2
        with:
          path: |
            target
            /usr/share/rust/.cargo/bin/
            /usr/share/rust/.cargo/registry/index/
            /usr/share/rust/.cargo/registry/cache/
            /usr/share/rust/.cargo/git/db/
          key: ${{ runner.OS }}-test-suite-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.OS }}-test-suite-
      - run: cargo test
